# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'R:\Projets\ERIC6\DBALBUMSQT5\DBALBUMS.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 1060)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 1060))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1250, 1040))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayoutcentral = QtWidgets.QGridLayout()
        self.gridLayoutcentral.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayoutcentral.setContentsMargins(0, 6, 0, 6)
        self.gridLayoutcentral.setSpacing(0)
        self.gridLayoutcentral.setObjectName("gridLayoutcentral")
        self.layout3table = QtWidgets.QGridLayout()
        self.layout3table.setContentsMargins(-1, 6, -1, 6)
        self.layout3table.setObjectName("layout3table")
        self.tbl_albums = QtWidgets.QTableView(self.centralwidget)
        self.tbl_albums.setStyleSheet("alternate-background-color: #D9D9D9;                                background-color: #E5E5E5;")
        self.tbl_albums.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tbl_albums.setAlternatingRowColors(True)
        self.tbl_albums.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_albums.setSortingEnabled(True)
        self.tbl_albums.setObjectName("tbl_albums")
        self.layout3table.addWidget(self.tbl_albums, 0, 0, 1, 1)
        self.gridLayoutcentral.addLayout(self.layout3table, 3, 0, 1, 1)
        self.layout4covertrack = QtWidgets.QHBoxLayout()
        self.layout4covertrack.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.layout4covertrack.setContentsMargins(0, 0, 0, 0)
        self.layout4covertrack.setObjectName("layout4covertrack")
        self.labelcover = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelcover.sizePolicy().hasHeightForWidth())
        self.labelcover.setSizePolicy(sizePolicy)
        self.labelcover.setMinimumSize(QtCore.QSize(400, 400))
        self.labelcover.setMaximumSize(QtCore.QSize(400, 400))
        self.labelcover.setBaseSize(QtCore.QSize(400, 400))
        self.labelcover.setScaledContents(True)
        self.labelcover.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelcover.setObjectName("labelcover")
        self.layout4covertrack.addWidget(self.labelcover)
        self.verticaltitletracks = QtWidgets.QVBoxLayout()
        self.verticaltitletracks.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticaltitletracks.setContentsMargins(6, 0, 0, 0)
        self.verticaltitletracks.setObjectName("verticaltitletracks")
        self.horizontaltitlescore = QtWidgets.QHBoxLayout()
        self.horizontaltitlescore.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontaltitlescore.setContentsMargins(5, 0, 5, 5)
        self.horizontaltitlescore.setObjectName("horizontaltitlescore")
        self.lab_album = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_album.sizePolicy().hasHeightForWidth())
        self.lab_album.setSizePolicy(sizePolicy)
        self.lab_album.setMinimumSize(QtCore.QSize(500, 0))
        self.lab_album.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lab_album.setAutoFillBackground(False)
        self.lab_album.setStyleSheet("border: 5px solid white;border-radius: 15px;")
        self.lab_album.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lab_album.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_album.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.lab_album.setObjectName("lab_album")
        self.horizontaltitlescore.addWidget(self.lab_album)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontaltitlescore.addItem(spacerItem)
        self.btn_scorealb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scorealb.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_scorealb.sizePolicy().hasHeightForWidth())
        self.btn_scorealb.setSizePolicy(sizePolicy)
        self.btn_scorealb.setMaximumSize(QtCore.QSize(50, 21))
        self.btn_scorealb.setFlat(False)
        self.btn_scorealb.setObjectName("btn_scorealb")
        self.horizontaltitlescore.addWidget(self.btn_scorealb)
        self.lab_scorealb = QtWidgets.QLabel(self.centralwidget)
        self.lab_scorealb.setObjectName("lab_scorealb")
        self.horizontaltitlescore.addWidget(self.lab_scorealb)
        self.sli_scorealb = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sli_scorealb.sizePolicy().hasHeightForWidth())
        self.sli_scorealb.setSizePolicy(sizePolicy)
        self.sli_scorealb.setMinimumSize(QtCore.QSize(100, 0))
        self.sli_scorealb.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sli_scorealb.setOrientation(QtCore.Qt.Horizontal)
        self.sli_scorealb.setObjectName("sli_scorealb")
        self.horizontaltitlescore.addWidget(self.sli_scorealb)
        self.verticaltitletracks.addLayout(self.horizontaltitlescore)
        self.tbl_tracks = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_tracks.sizePolicy().hasHeightForWidth())
        self.tbl_tracks.setSizePolicy(sizePolicy)
        self.tbl_tracks.setStyleSheet("alternate-background-color: #D9D9D9;                                background-color: #E5E5E5;")
        self.tbl_tracks.setAlternatingRowColors(True)
        self.tbl_tracks.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_tracks.setObjectName("tbl_tracks")
        self.verticaltitletracks.addWidget(self.tbl_tracks)
        self.horizontalscoretrk = QtWidgets.QHBoxLayout()
        self.horizontalscoretrk.setContentsMargins(0, 8, 0, 8)
        self.horizontalscoretrk.setObjectName("horizontalscoretrk")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalscoretrk.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalscoretrk.addItem(spacerItem2)
        self.btn_scoretrk = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scoretrk.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_scoretrk.sizePolicy().hasHeightForWidth())
        self.btn_scoretrk.setSizePolicy(sizePolicy)
        self.btn_scoretrk.setMinimumSize(QtCore.QSize(50, 21))
        self.btn_scoretrk.setMaximumSize(QtCore.QSize(50, 21))
        self.btn_scoretrk.setObjectName("btn_scoretrk")
        self.horizontalscoretrk.addWidget(self.btn_scoretrk)
        self.lab_scoretrk = QtWidgets.QLabel(self.centralwidget)
        self.lab_scoretrk.setObjectName("lab_scoretrk")
        self.horizontalscoretrk.addWidget(self.lab_scoretrk)
        self.sli_scoretrk = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sli_scoretrk.sizePolicy().hasHeightForWidth())
        self.sli_scoretrk.setSizePolicy(sizePolicy)
        self.sli_scoretrk.setMinimumSize(QtCore.QSize(100, 0))
        self.sli_scoretrk.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sli_scoretrk.setOrientation(QtCore.Qt.Horizontal)
        self.sli_scoretrk.setObjectName("sli_scoretrk")
        self.horizontalscoretrk.addWidget(self.sli_scoretrk)
        self.verticaltitletracks.addLayout(self.horizontalscoretrk)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticaltitletracks.addWidget(self.line)
        self.horizontalplayer = QtWidgets.QHBoxLayout()
        self.horizontalplayer.setContentsMargins(5, 5, 5, 5)
        self.horizontalplayer.setObjectName("horizontalplayer")
        self.prevBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prevBtn.setStyleSheet("")
        self.prevBtn.setText("")
        self.prevBtn.setFlat(True)
        self.prevBtn.setObjectName("prevBtn")
        self.horizontalplayer.addWidget(self.prevBtn)
        self.playBtn = QtWidgets.QPushButton(self.centralwidget)
        self.playBtn.setStyleSheet("")
        self.playBtn.setText("")
        self.playBtn.setFlat(True)
        self.playBtn.setObjectName("playBtn")
        self.horizontalplayer.addWidget(self.playBtn)
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setStyleSheet("")
        self.stopBtn.setText("")
        self.stopBtn.setFlat(True)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalplayer.addWidget(self.stopBtn)
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setStyleSheet("")
        self.nextBtn.setText("")
        self.nextBtn.setFlat(True)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalplayer.addWidget(self.nextBtn)
        self.seekSliderLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.seekSliderLabel1.setObjectName("seekSliderLabel1")
        self.horizontalplayer.addWidget(self.seekSliderLabel1)
        self.seekSlider = QtWidgets.QSlider(self.centralwidget)
        self.seekSlider.setOrientation(QtCore.Qt.Horizontal)
        self.seekSlider.setObjectName("seekSlider")
        self.horizontalplayer.addWidget(self.seekSlider)
        self.seekSliderLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.seekSliderLabel2.setObjectName("seekSliderLabel2")
        self.horizontalplayer.addWidget(self.seekSliderLabel2)
        self.infoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.infoBtn.setStyleSheet("")
        self.infoBtn.setText("")
        self.infoBtn.setFlat(True)
        self.infoBtn.setObjectName("infoBtn")
        self.horizontalplayer.addWidget(self.infoBtn)
        self.volumeDescBtn = QtWidgets.QPushButton(self.centralwidget)
        self.volumeDescBtn.setStyleSheet("")
        self.volumeDescBtn.setFlat(True)
        self.volumeDescBtn.setObjectName("volumeDescBtn")
        self.horizontalplayer.addWidget(self.volumeDescBtn)
        self.volumeIncBtn = QtWidgets.QPushButton(self.centralwidget)
        self.volumeIncBtn.setStyleSheet("")
        self.volumeIncBtn.setFlat(True)
        self.volumeIncBtn.setObjectName("volumeIncBtn")
        self.horizontalplayer.addWidget(self.volumeIncBtn)
        self.verticaltitletracks.addLayout(self.horizontalplayer)
        self.layout4covertrack.addLayout(self.verticaltitletracks)
        self.gridLayoutcentral.addLayout(self.layout4covertrack, 5, 0, 1, 1)
        self.layout2thunbnails = QtWidgets.QGridLayout()
        self.layout2thunbnails.setObjectName("layout2thunbnails")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 310))
        self.scrollArea.setSizeIncrement(QtCore.QSize(151, 151))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetthunbnails = QtWidgets.QWidget()
        self.scrollAreaWidgetthunbnails.setGeometry(QtCore.QRect(0, 0, 1260, 312))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetthunbnails.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetthunbnails.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetthunbnails.setMinimumSize(QtCore.QSize(1260, 312))
        self.scrollAreaWidgetthunbnails.setObjectName("scrollAreaWidgetthunbnails")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetthunbnails)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridthunbnails = QtWidgets.QGridLayout()
        self.gridthunbnails.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridthunbnails.setContentsMargins(3, 5, -1, 5)
        self.gridthunbnails.setSpacing(1)
        self.gridthunbnails.setObjectName("gridthunbnails")
        self.gridLayout_2.addLayout(self.gridthunbnails, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetthunbnails)
        self.layout2thunbnails.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.layout1command = QtWidgets.QHBoxLayout()
        self.layout1command.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout1command.setContentsMargins(0, 0, 0, 6)
        self.layout1command.setSpacing(5)
        self.layout1command.setObjectName("layout1command")
        self.lab_search = QtWidgets.QLabel(self.centralwidget)
        self.lab_search.setObjectName("lab_search")
        self.layout1command.addWidget(self.lab_search)
        self.lin_search = QtWidgets.QLineEdit(self.centralwidget)
        self.lin_search.setMinimumSize(QtCore.QSize(200, 0))
        self.lin_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lin_search.setObjectName("lin_search")
        self.layout1command.addWidget(self.lin_search)
        self.btn_clearsearch = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clearsearch.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_clearsearch.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_clearsearch.setBaseSize(QtCore.QSize(20, 0))
        self.btn_clearsearch.setObjectName("btn_clearsearch")
        self.layout1command.addWidget(self.btn_clearsearch)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_search.setObjectName("btn_search")
        self.layout1command.addWidget(self.btn_search)
        self.chb_searchtracks = QtWidgets.QCheckBox(self.centralwidget)
        self.chb_searchtracks.setObjectName("chb_searchtracks")
        self.layout1command.addWidget(self.chb_searchtracks)
        self.com_category = QtWidgets.QComboBox(self.centralwidget)
        self.com_category.setMinimumSize(QtCore.QSize(80, 0))
        self.com_category.setObjectName("com_category")
        self.layout1command.addWidget(self.com_category)
        self.com_family = QtWidgets.QComboBox(self.centralwidget)
        self.com_family.setMinimumSize(QtCore.QSize(80, 0))
        self.com_family.setObjectName("com_family")
        self.layout1command.addWidget(self.com_family)
        self.com_label = QtWidgets.QComboBox(self.centralwidget)
        self.com_label.setMinimumSize(QtCore.QSize(80, 0))
        self.com_label.setCurrentText("")
        self.com_label.setObjectName("com_label")
        self.layout1command.addWidget(self.com_label)
        self.com_year = QtWidgets.QComboBox(self.centralwidget)
        self.com_year.setMinimumSize(QtCore.QSize(80, 0))
        self.com_year.setObjectName("com_year")
        self.layout1command.addWidget(self.com_year)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout1command.addItem(spacerItem3)
        self.btn_notreeview = QtWidgets.QPushButton(self.centralwidget)
        self.btn_notreeview.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_notreeview.setObjectName("btn_notreeview")
        self.layout1command.addWidget(self.btn_notreeview)
        self.com_envt = QtWidgets.QComboBox(self.centralwidget)
        self.com_envt.setMinimumSize(QtCore.QSize(80, 0))
        self.com_envt.setObjectName("com_envt")
        self.layout1command.addWidget(self.com_envt)
        self.layout2thunbnails.addLayout(self.layout1command, 0, 0, 1, 1)
        self.gridLayoutcentral.addLayout(self.layout2thunbnails, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayoutcentral)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.com_category.setCurrentIndex(-1)
        self.com_family.setCurrentIndex(-1)
        self.com_label.setCurrentIndex(-1)
        self.com_year.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DBAlbumMain"))
        self.labelcover.setText(_translate("MainWindow", "TextLabel"))
        self.btn_scorealb.setText(_translate("MainWindow", "Update"))
        self.lab_scorealb.setText(_translate("MainWindow", "☆☆☆"))
        self.btn_scoretrk.setText(_translate("MainWindow", "Update"))
        self.lab_scoretrk.setText(_translate("MainWindow", "☆☆☆"))
        self.seekSliderLabel1.setText(_translate("MainWindow", "TextLabel"))
        self.seekSliderLabel2.setText(_translate("MainWindow", "TextLabel"))
        self.volumeDescBtn.setText(_translate("MainWindow", "▼"))
        self.volumeIncBtn.setText(_translate("MainWindow", "▲"))
        self.lab_search.setText(_translate("MainWindow", "Search"))
        self.btn_clearsearch.setText(_translate("MainWindow", "✖"))
        self.btn_search.setText(_translate("MainWindow", "➜"))
        self.chb_searchtracks.setText(_translate("MainWindow", "Search in tracks"))
        self.btn_notreeview.setText(_translate("MainWindow", "≠"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

