# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'R:\Projets\ERIC6\DBALBUMSQT5\DBLOADING.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoadingWindow(object):
    def setupUi(self, LoadingWindow):
        LoadingWindow.setObjectName("LoadingWindow")
        LoadingWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        LoadingWindow.resize(400, 350)
        self.verticalLayoutWidget = QtWidgets.QWidget(LoadingWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lab_title.setMinimumSize(QtCore.QSize(100, 100))
        self.lab_title.setMaximumSize(QtCore.QSize(100, 100))
        self.lab_title.setText("")
        self.lab_title.setPixmap(QtGui.QPixmap("//homerstation/_LossLess/_INVENT/DBAlbums/DBAlbums.png"))
        self.lab_title.setScaledContents(True)
        self.lab_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_title.setObjectName("lab_title")
        self.horizontalLayout.addWidget(self.lab_title)
        self.lab_logo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lab_logo.setScaledContents(False)
        self.lab_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_logo.setObjectName("lab_logo")
        self.horizontalLayout.addWidget(self.lab_logo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setStyleSheet("alternate-background-color: #D9D9D9;                                background-color: #E5E5E5;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setAccessibleName("")
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableWid1 = QtWidgets.QTableView(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWid1.sizePolicy().hasHeightForWidth())
        self.tableWid1.setSizePolicy(sizePolicy)
        self.tableWid1.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWid1.setStyleSheet("alternate-background-color: #D9D9D9;                                background-color: #E5E5E5;")
        self.tableWid1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWid1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWid1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWid1.setAlternatingRowColors(True)
        self.tableWid1.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWid1.setObjectName("tableWid1")
        self.gridLayout.addWidget(self.tableWid1, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWid2 = QtWidgets.QTableView(self.tab_2)
        self.tableWid2.setAlternatingRowColors(True)
        self.tableWid2.setObjectName("tableWid2")
        self.gridLayout_3.addWidget(self.tableWid2, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWid3 = QtWidgets.QTableView(self.tab_3)
        self.tableWid3.setStyleSheet("alternate-background-color: #D9D9D9;                                background-color: #E5E5E5;")
        self.tableWid3.setAlternatingRowColors(True)
        self.tableWid3.setObjectName("tableWid3")
        self.gridLayout_5.addWidget(self.tableWid3, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.btn_quit = QtWidgets.QPushButton(LoadingWindow)
        self.btn_quit.setGeometry(QtCore.QRect(375, 4, 20, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_quit.sizePolicy().hasHeightForWidth())
        self.btn_quit.setSizePolicy(sizePolicy)
        self.btn_quit.setBaseSize(QtCore.QSize(20, 24))
        self.btn_quit.setObjectName("btn_quit")

        self.retranslateUi(LoadingWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoadingWindow)

    def retranslateUi(self, LoadingWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadingWindow.setWindowTitle(_translate("LoadingWindow", "Form"))
        self.lab_logo.setText(_translate("LoadingWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("LoadingWindow", "Style"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LoadingWindow", "Volume"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("LoadingWindow", "Year"))
        self.btn_quit.setText(_translate("LoadingWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadingWindow = QtWidgets.QWidget()
    ui = Ui_LoadingWindow()
    ui.setupUi(LoadingWindow)
    LoadingWindow.show()
    sys.exit(app.exec_())

