# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'R:\Python\DBAlbums\DBALBUMS.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 1060)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 1060))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1250, 1040))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayoutcentral = QtWidgets.QGridLayout()
        self.gridLayoutcentral.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayoutcentral.setContentsMargins(0, 0, 0, 6)
        self.gridLayoutcentral.setSpacing(0)
        self.gridLayoutcentral.setObjectName("gridLayoutcentral")
        self.layout4covertrack = QtWidgets.QHBoxLayout()
        self.layout4covertrack.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.layout4covertrack.setContentsMargins(0, 0, 0, 0)
        self.layout4covertrack.setObjectName("layout4covertrack")
        self.framecover = QtWidgets.QFrame(self.centralwidget)
        self.framecover.setMinimumSize(QtCore.QSize(400, 400))
        self.framecover.setMaximumSize(QtCore.QSize(400, 400))
        self.framecover.setStyleSheet("border: 1px solid black;")
        self.framecover.setLineWidth(0)
        self.framecover.setObjectName("framecover")
        self.coverLayout = QtWidgets.QVBoxLayout(self.framecover)
        self.coverLayout.setContentsMargins(0, 0, 0, 7)
        self.coverLayout.setSpacing(0)
        self.coverLayout.setObjectName("coverLayout")
        self.layout4covertrack.addWidget(self.framecover)
        self.verticaltitletracks = QtWidgets.QVBoxLayout()
        self.verticaltitletracks.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticaltitletracks.setContentsMargins(6, 0, 0, 0)
        self.verticaltitletracks.setObjectName("verticaltitletracks")
        self.horizontaltitlescore = QtWidgets.QHBoxLayout()
        self.horizontaltitlescore.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontaltitlescore.setContentsMargins(5, 0, 5, 5)
        self.horizontaltitlescore.setSpacing(7)
        self.horizontaltitlescore.setObjectName("horizontaltitlescore")
        self.lab_album = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_album.sizePolicy().hasHeightForWidth())
        self.lab_album.setSizePolicy(sizePolicy)
        self.lab_album.setMinimumSize(QtCore.QSize(500, 60))
        self.lab_album.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lab_album.setBaseSize(QtCore.QSize(0, 0))
        self.lab_album.setAutoFillBackground(False)
        self.lab_album.setStyleSheet("")
        self.lab_album.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lab_album.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_album.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.lab_album.setReadOnly(True)
        self.lab_album.setObjectName("lab_album")
        self.horizontaltitlescore.addWidget(self.lab_album)
        self.lab_label = QtWidgets.QLabel(self.centralwidget)
        self.lab_label.setMinimumSize(QtCore.QSize(0, 60))
        self.lab_label.setMaximumSize(QtCore.QSize(100, 60))
        self.lab_label.setStyleSheet("")
        self.lab_label.setText("")
        self.lab_label.setScaledContents(True)
        self.lab_label.setObjectName("lab_label")
        self.horizontaltitlescore.addWidget(self.lab_label)
        self.btn_scorealb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scorealb.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_scorealb.sizePolicy().hasHeightForWidth())
        self.btn_scorealb.setSizePolicy(sizePolicy)
        self.btn_scorealb.setMinimumSize(QtCore.QSize(40, 21))
        self.btn_scorealb.setMaximumSize(QtCore.QSize(0, 21))
        self.btn_scorealb.setStyleSheet("background-color: darkgrey;")
        self.btn_scorealb.setText("")
        self.btn_scorealb.setFlat(False)
        self.btn_scorealb.setObjectName("btn_scorealb")
        self.horizontaltitlescore.addWidget(self.btn_scorealb)
        self.lab_scorealb = QtWidgets.QLabel(self.centralwidget)
        self.lab_scorealb.setObjectName("lab_scorealb")
        self.horizontaltitlescore.addWidget(self.lab_scorealb)
        self.sli_scorealb = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sli_scorealb.sizePolicy().hasHeightForWidth())
        self.sli_scorealb.setSizePolicy(sizePolicy)
        self.sli_scorealb.setMinimumSize(QtCore.QSize(100, 0))
        self.sli_scorealb.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sli_scorealb.setOrientation(QtCore.Qt.Horizontal)
        self.sli_scorealb.setObjectName("sli_scorealb")
        self.horizontaltitlescore.addWidget(self.sli_scorealb)
        self.verticaltitletracks.addLayout(self.horizontaltitlescore)
        self.tbl_tracks = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_tracks.sizePolicy().hasHeightForWidth())
        self.tbl_tracks.setSizePolicy(sizePolicy)
        self.tbl_tracks.setMinimumSize(QtCore.QSize(0, 0))
        self.tbl_tracks.setMaximumSize(QtCore.QSize(16777215, 270))
        self.tbl_tracks.setStyleSheet("")
        self.tbl_tracks.setAlternatingRowColors(True)
        self.tbl_tracks.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_tracks.setSortingEnabled(True)
        self.tbl_tracks.setObjectName("tbl_tracks")
        self.verticaltitletracks.addWidget(self.tbl_tracks)
        self.horizontalscoretrk = QtWidgets.QHBoxLayout()
        self.horizontalscoretrk.setContentsMargins(0, 8, 0, 8)
        self.horizontalscoretrk.setObjectName("horizontalscoretrk")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalscoretrk.addItem(spacerItem)
        self.btn_scoretrk = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scoretrk.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_scoretrk.sizePolicy().hasHeightForWidth())
        self.btn_scoretrk.setSizePolicy(sizePolicy)
        self.btn_scoretrk.setMinimumSize(QtCore.QSize(40, 21))
        self.btn_scoretrk.setMaximumSize(QtCore.QSize(0, 21))
        self.btn_scoretrk.setStyleSheet("background-color: darkgrey;")
        self.btn_scoretrk.setText("")
        self.btn_scoretrk.setFlat(False)
        self.btn_scoretrk.setObjectName("btn_scoretrk")
        self.horizontalscoretrk.addWidget(self.btn_scoretrk)
        self.lab_scoretrk = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_scoretrk.sizePolicy().hasHeightForWidth())
        self.lab_scoretrk.setSizePolicy(sizePolicy)
        self.lab_scoretrk.setObjectName("lab_scoretrk")
        self.horizontalscoretrk.addWidget(self.lab_scoretrk)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalscoretrk.addItem(spacerItem1)
        self.sli_scoretrk = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sli_scoretrk.sizePolicy().hasHeightForWidth())
        self.sli_scoretrk.setSizePolicy(sizePolicy)
        self.sli_scoretrk.setMinimumSize(QtCore.QSize(100, 0))
        self.sli_scoretrk.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sli_scoretrk.setOrientation(QtCore.Qt.Horizontal)
        self.sli_scoretrk.setObjectName("sli_scoretrk")
        self.horizontalscoretrk.addWidget(self.sli_scoretrk)
        self.verticaltitletracks.addLayout(self.horizontalscoretrk)
        self.layout4covertrack.addLayout(self.verticaltitletracks)
        self.gridLayoutcentral.addLayout(self.layout4covertrack, 6, 0, 1, 1)
        self.layout2thunbnails = QtWidgets.QGridLayout()
        self.layout2thunbnails.setSpacing(0)
        self.layout2thunbnails.setObjectName("layout2thunbnails")
        self.gridLayoutcentral.addLayout(self.layout2thunbnails, 1, 0, 1, 1)
        self.layout3table = QtWidgets.QGridLayout()
        self.layout3table.setContentsMargins(-1, 6, -1, 6)
        self.layout3table.setObjectName("layout3table")
        self.tbl_albums = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_albums.sizePolicy().hasHeightForWidth())
        self.tbl_albums.setSizePolicy(sizePolicy)
        self.tbl_albums.setStyleSheet("")
        self.tbl_albums.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tbl_albums.setAlternatingRowColors(True)
        self.tbl_albums.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_albums.setSortingEnabled(True)
        self.tbl_albums.setObjectName("tbl_albums")
        self.layout3table.addWidget(self.tbl_albums, 0, 0, 1, 1)
        self.gridLayoutcentral.addLayout(self.layout3table, 4, 0, 1, 1)
        self.layout1command = QtWidgets.QHBoxLayout()
        self.layout1command.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout1command.setContentsMargins(0, 0, 0, 6)
        self.layout1command.setSpacing(5)
        self.layout1command.setObjectName("layout1command")
        self.lab_search = QtWidgets.QLabel(self.centralwidget)
        self.lab_search.setObjectName("lab_search")
        self.layout1command.addWidget(self.lab_search)
        self.lin_search = QtWidgets.QLineEdit(self.centralwidget)
        self.lin_search.setMinimumSize(QtCore.QSize(200, 0))
        self.lin_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lin_search.setObjectName("lin_search")
        self.layout1command.addWidget(self.lin_search)
        self.btn_clearsearch = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clearsearch.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_clearsearch.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_clearsearch.setBaseSize(QtCore.QSize(20, 0))
        self.btn_clearsearch.setStyleSheet("border: none;")
        self.btn_clearsearch.setText("")
        self.btn_clearsearch.setFlat(False)
        self.btn_clearsearch.setObjectName("btn_clearsearch")
        self.layout1command.addWidget(self.btn_clearsearch)
        self.chb_searchtracks = QtWidgets.QCheckBox(self.centralwidget)
        self.chb_searchtracks.setObjectName("chb_searchtracks")
        self.layout1command.addWidget(self.chb_searchtracks)
        self.com_category = QtWidgets.QComboBox(self.centralwidget)
        self.com_category.setMinimumSize(QtCore.QSize(0, 0))
        self.com_category.setObjectName("com_category")
        self.layout1command.addWidget(self.com_category)
        self.com_family = QtWidgets.QComboBox(self.centralwidget)
        self.com_family.setMinimumSize(QtCore.QSize(0, 0))
        self.com_family.setObjectName("com_family")
        self.layout1command.addWidget(self.com_family)
        self.com_genres = QtWidgets.QComboBox(self.centralwidget)
        self.com_genres.setMinimumSize(QtCore.QSize(0, 0))
        self.com_genres.setObjectName("com_genres")
        self.layout1command.addWidget(self.com_genres)
        self.com_label = QtWidgets.QComboBox(self.centralwidget)
        self.com_label.setMinimumSize(QtCore.QSize(0, 0))
        self.com_label.setCurrentText("")
        self.com_label.setObjectName("com_label")
        self.layout1command.addWidget(self.com_label)
        self.com_year = QtWidgets.QComboBox(self.centralwidget)
        self.com_year.setMinimumSize(QtCore.QSize(0, 0))
        self.com_year.setObjectName("com_year")
        self.layout1command.addWidget(self.com_year)
        self.com_country = QtWidgets.QComboBox(self.centralwidget)
        self.com_country.setObjectName("com_country")
        self.layout1command.addWidget(self.com_country)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout1command.addItem(spacerItem2)
        self.lab_comenvt = QtWidgets.QLabel(self.centralwidget)
        self.lab_comenvt.setText("")
        self.lab_comenvt.setObjectName("lab_comenvt")
        self.layout1command.addWidget(self.lab_comenvt)
        self.com_envt = QtWidgets.QComboBox(self.centralwidget)
        self.com_envt.setMinimumSize(QtCore.QSize(80, 0))
        self.com_envt.setObjectName("com_envt")
        self.layout1command.addWidget(self.com_envt)
        self.gridLayoutcentral.addLayout(self.layout1command, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayoutcentral)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.com_category.setCurrentIndex(-1)
        self.com_family.setCurrentIndex(-1)
        self.com_label.setCurrentIndex(-1)
        self.com_year.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DBAlbumMain"))
        self.lab_scorealb.setText(_translate("MainWindow", "☆☆☆"))
        self.lab_scoretrk.setText(_translate("MainWindow", "☆☆☆"))
        self.lab_search.setText(_translate("MainWindow", "Search"))
        self.chb_searchtracks.setText(_translate("MainWindow", "Search in tracks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
