SELECT DBALBUMS.ID_CD, Name, NameTAG FROM DBALBUMS 
	INNER JOIN 
	(SELECT ID_CD, CONCAT(MAX(CASE WHEN TAg_Albumartists='' THEN TAG_Artists ELSE TAg_Albumartists END)," - ", MAX(TAG_Album)) AS NameTAG
		FROM DBTRACKS
		GROUP BY ID_CD) LL
	ON DBALBUMS.ID_CD=LL.ID_CD
	
	
