-- no covers x3147 / x0994 no cover find
SELECT * FROM DBALBUMS WHERE Cover='No Picture';
SELECT * FROM DBALBUMS WHERE Cover='No Picture' AND Qty_covers>1;

-- no tags x517
SELECT DISTINCT DBALBUMS.* FROM DBALBUMS 
	INNER JOIN DBTRACKS 
	ON DBALBUMS.ID_CD=DBTRACKS.ID_CD AND TAG_Artists='';

-- no year x243
SELECT * FROM DBALBUMS WHERE year IS NULL OR Year='' OR Year ='????' OR Year =0;

-- general
SELECT 
(SELECT COUNT(*) FROM DBALBUMS) AS ALBUM_TOTAL,
(SELECT COUNT(*) FROM DBALBUMS WHERE Cover='No Picture') AS COVER_MISSING,
(SELECT COUNT(*) FROM DBALBUMS WHERE year IS NULL OR Year='' OR Year ='????' OR Year=0) AS YEAR_MISSING,
(SELECT COUNT(*) FROM (SELECT DISTINCT ID_CD, TAG_Artists FROM DBTRACKS WHERE TAG_Artists IS NULL OR TAG_Artists="") LL) AS TAGS_MISSING;

-- cumul 3 probs x11
SELECT DISTINCT DBALBUMS.* FROM DBALBUMS 
	INNER JOIN DBTRACKS 
	ON DBALBUMS.ID_CD=DBTRACKS.ID_CD AND (TAG_Artists IS NULL OR TAG_Artists='')
WHERE Cover='No Picture' AND (year IS NULL OR Year='' OR Year ='????' OR Year=0);



