-- 13393 ALBUMS
SELECT * FROM ALBUMS;

-- TYPE MEDIA
SELECT TYPEMEDIA, COUNT(*) FROM TRACKS GROUP BY TYPEMEDIA;
SELECT * FROM TRACKS WHERE TYPEMEDIA = 'audio/mp2';

-- 418 NO TAG ARTISTS
SELECT * FROM ALBUMS WHERE ARTIST IS NULL;

-- 1874 NO TAG NUMBER TRACK
SELECT DISTINCT ALBUMS.* FROM ALBUMS
INNER JOIN TRACKS
ON TRACKS.ID_CD = ALBUMS.ID_CD
WHERE TRACKORDER IS NULL;

-- 147 NO TAG YEAR
SELECT * FROM ALBUMS WHERE year IS NULL OR Year='' OR Year='????' OR Year =0;

-- 7 ALBUMS WITH BAD FILE TRACKS
SELECT * FROM ALBUMS
INNER JOIN (SELECT ID_CD, COUNT(*) AS NBTRK FROM TRACKS GROUP BY ID_CD) TR
ON TR.ID_CD = ALBUMS.ID_CD
WHERE NBTRK<>AUDIOTRACKS AND TAGMETHOD = 'TAG';

-- 44 COVER EXIST PROBLEM
SELECT * FROM ALBUMS
LEFT JOIN COVERS 
ON ALBUMS.ID_CD = COVERS.ID_CD
WHERE COVERS.ID_CD IS NULL AND ALBUMS.COVER<>'<No Picture>';

-- 2165 NO COVER
SELECT * FROM ALBUMS WHERE PIC = 0;

-- 1722 MORE CHOICE COVER
SELECT * FROM ALBUMS
WHERE PIC > 0 AND ALBUMS.COVER='<No Picture>';
