
-- 01 INTEGRITY ORPHAN ALBUMS (NO TRACKS)
DELETE 
FROM ALBUMS 
WHERE ALBUMS.ID_CD  NOT IN (SELECT DISTINCT TRACKS.ID_CD FROM TRACKS);

-- 02 INTEGRITY ORPHAN TRACKS
DELETE 
FROM TRACKS 
WHERE TRACKS.ID_CD  NOT IN (SELECT DISTINCT ALBUMS.ID_CD FROM ALBUMS);

-- 03 INTEGRITY ORPHAN COVERS
DELETE 
FROM COVERS 
WHERE COVERS.ID_CD  NOT IN (SELECT DISTINCT ALBUMS.ID_CD FROM ALBUMS);

