-- --------------------------------------------------------
-- Hôte:                         HOMERSTATION
-- Version du serveur:           5.5.53-MariaDB - Source distribution
-- Serveur OS:                   Linux
-- HeidiSQL Version:             9.1.0.4867
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Export de la structure de table InventMP3. DBFOOBOR
CREATE TABLE IF NOT EXISTS `DBFOOBOR` (
  `FIL_TRACK` varchar(160) DEFAULT NULL,
  `FIL_TRACKM` varchar(160) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Export de données de la table InventMP3.DBFOOBOR: ~165 rows (environ)
DELETE FROM `DBFOOBOR`;
/*!40000 ALTER TABLE `DBFOOBOR` DISABLE KEYS */;
INSERT INTO `DBFOOBOR` (`FIL_TRACK`, `FIL_TRACKM`) VALUES
	('Klopfgeister - Are You free.mp3', '%Klopfgeister%Are%You%free%'),
	('01-weekend_heroes_-_uncover-eup.mp3', '%weekend%heroes%uncover%'),
	('07-extrawelt-pontiac_(original_mix)-wws.mp3', '%extrawelt%pontiac%'),
	('Teddy Sambuki-Passion      Original Mix -www.mrtzcmp3.net.mp3', '%Teddy%Sambuki%Passion%'),
	('Mononoid - Protoplasm (Moonbeam Remix) www.community-music-dj.com.mp3', '%Mononoid%Protoplasm%Moonbeam%'),
	('Nicolas Cuer - Strongly_Disagree_Original_Mix.mp3', '%Nicolas%Cuer%Strongly%'),
	('Sergio Mega - To Catch The Last Train (Yan Oxygen Remix).mp3', '%Sergio%Mega%Catch%'),
	('109-rocky_and_sphera_-_echo_(yotopia_remix)-gem.mp3', '%rocky%sphera%echo%'),
	('201-atmos_-_only_for_you_(phaxe_remix)-gem.mp3', '%atmos%only%for%you%phaxe%remix%'),
	('05-haldolium_-_photographic-gem_5_54.mp3', '%haldolium%photographic%'),
	('02-haldolium_-_haldolium-two_roads-eup.mp3', '%haldolium%two%road%'),
	('10. Cold Blue - Lucidity - Edit++++++.mp3', '%Cold%Blue%Lucidity%'),
	('01-critical_choice--harbour_candy_(davinci_code_remix)-shelter.mp3', '%critical%choice%harbour%'),
	('01_-_04. Frost Raven - Poltergeist.mp3', '%Frost%Raven%Poltergeist%'),
	('02_-_05-cyklones_-_green_view.mp3', '%cyklones%green%view%'),
	('03_-_08-innershade_-_vibration-mycel.mp3', '%innershade%vibration%'),
	('04_-_01-mr.what-candy_maker.mp3', '%what%candy%maker%'),
	('05_-_Rollercoaster - Nocturnal Life (free) - 02 Tres Dias en la Oscuridad.mp3', '%Tres%Dias%Oscuridad%'),
	('06_-_01 Have a Nice Day.mp3', '%Have%Nice%Day%'),
	('07_-_01-e-clip_-_artificial_intelligence-eup.mp3', '%clip%artificial%intelligence%'),
	('08_-_01-staga_d1sh-oniero_sheep.mp3', '%staga%d1sh%oniero%sheep%'),
	('09_-_03.  Static Movement - Me Gusta.mp3', ' %Static%Movement%Me%Gusta%'),
	('10_-_02. Capital Monkey - Diethylamide.mp3', '%Capital%Monkey%Diethylamide%'),
	('11_-_02. Frost Raven - Mana.mp3', '%Frost Raven%Mana%'),
	('12_-_06-bio-psy_-_meloncholy.mp3', '%bio%psy%meloncholy%'),
	('13_-_Pixel_Vs_Tristan-High_By_Defin.mp3', '%Pixel%Tristan%High%Defin%'),
	('14_-_01-headroom_and_avalon_-_mind_fk-eup.mp3', '%headroom%avalon%mind%'),
	('15_-_U-Recken-May All Beings Be Happy(myfreemp3.eu).mp3', '%Recken%May%Beings%'),
	('16_-_102-sonitus_project_-_true_travel_to_planet_lajkica-br.mp3', '%sonitus%project%true%travel%'),
	('17_-_8-magnus-signal_strength.mp3', '%magnus%signal%strength%'),
	('18_-_01-ghebro_-_on_acid-br.mp3', '%ghebro%acid%'),
	('19_-_101-digital_tribe_vs_radioactive_project_-_dance_world-br_DEBUT30.mp3', '%digital%tribe%radioactive%'),
	('20_-_0-shift_-_p_s_u._original_mix.mp3', '%shift%original%mix%'),
	('21_-_02-chichke_-_magic_carpet-fym.mp3', '%chichke%magic%carpet%'),
	('22_-_01 Analyzer - Psychedelic Analyzing_02-19.mp3', '%Analyzer%Psychedelic%Analyzing%'),
	('23_-_01-chichke_-_rock_harder-fym.mp3', '%chichke%rock%harder%'),
	('24_-_05 Empty Heads - Sturdy Pete++++++.mp3', '%Empty%Heads%Sturdy%Pete%'),
	('25_-_10_Plaxius_-_Twisted_Dream.mp3', '%Plaxius%Twisted%Dream%'),
	('01 - 01-timelock_-_timelock_and_invisible_reality_-_wildfire-eup.mp3', '%timelock%invisible%reality%wildfire%'),
	('02 - 02-egorythmia_-_arctic_dawn_(d-addiction_remix)-gem.mp3', '%egorythmia%arctic%dawn%'),
	('03 - 17. Sideform - Shuttle.mp3', '%Sideform%Shuttle%'),
	('04 - 02-tezla_-_scary_stuff-eup.mp3', '%tezla%scary%stuff%'),
	('05 - 01-aerospace-another_way_(original_mix).mp3', '%aerospace%another%way%'),
	('06 - 01-tezla_-_8_bit_power-eup.mp3', '%tezla%8%bit%power%'),
	('07 - 02-spacecat_and_pixel_-_the_experiment-eup.mp3', '%spacecat%pixel%experiment%'),
	('08 - 01-unseen_dimensions_and_shake_-_laughter-gem.mp3', '%unseen%dimensions%shake%laughter%'),
	('09 - 03-aerospace-major_tease.mp3', '%aerospace%major%tease%'),
	('10 - 03-morten_granau_-_pixel_andfreedom_fighters-trick_n._treat_(morten_granau_remix)-eup.mp3', '%morten%granau%pixel%fighters%trick%'),
	('11 - 01-gaudium_-_answers-gem.mp3', '%gaudium%answers%'),
	('12 - 02-black_mesa_glassjaw_genetrick_-_time_and_space-eup.mp3', '%mesa%glassjaw%genetrick%time%space%'),
	('13 - VA - Party Pack - 02 - Symphonix & Class A - Experimental Game (Class A rmx) [F#m - 136].mp3', '%Symphonix%Class% Experimental%Game%'),
	('14 - 2.Durs - Fireball.mp3', '%Durs%Fireball%'),
	('15 - 02.kopel_-_darkness-eup.mp3', '%kopel%darkness%'),
	('16 - 04-coming_soon_-_into_space-eup.mp3', '%coming%soon%into%space%'),
	('17- 6.Odiseo - La Pelo.mp3', '%Odiseo%Pelo%'),
	('18 - 01-morten_granau_-_morten_granau-new_world_order-eup.mp3', '%morten%granau%new%world%order%'),
	('19 - 01-kronfeld_-_the_voicer-eup.mp3', '%kronfeld%voicer%'),
	('20 - 9. Durs - Calculator.mp3', '%Durs%Calculator%'),
	('21 - 02-darma-deep_hole_(ghost_rider_rmx).mp3', '%darma%deep%hole%'),
	('22 - 01-copycat_groovaholik_-_the_path-eup.mp3', '%copycat%groovaholik%path%'),
	('23 - 05-d-vision_-_another_planet.mp3', '%vision%another%planet%'),
	('24 - 4201568_Odd_Moves_Original_Mix (1).mp3', '%Odd%Moves%Original%Mix'),
	('25 - Neelix   Sorrow.mp3', '%Neelix%Sorrow%'),
	('26 - 107-sensifeel-hamburger_royal-eup.mp3', '%sensifeel%hamburger%royal%'),
	('27 - 01-audiophonic_-_hi_kids_(eminem_vocals )_(re-make)-(PROMO)-web-2013-eup.mp3', '%audiophonic%kids%'),
	('01-xahno_-_flying_dance-eup.mp3', '%xahno%flying%dance%'),
	('01-suntree_and_antigravity_-_o-beat-gem.mp3', '%suntree%antigravity%beat%'),
	('Phaxe & Morten Granau - Beatless.mp3', '%Phaxe%Morten%Granau%Beatless%'),
	('05-beat_bizarre-tungsten.mp3', '%beat%bizarre%tungsten%'),
	('03-new_age_osher-raising_ecstasy.mp3', '%osher%raising%ecstasy%'),
	('02-osher-self_control.mp3', '%osher%self%control%'),
	('Xahno_-_Sound_Dreamer_Original_Mix.mp3', '%Xahno%Sound%Dreamer%'),
	('02-kingpink_-_shalom-gem.mp3', '%kingpink%shalom%'),
	('03-e-clip_and_egorythmia_-_new_level_of_being_(skyfall_remix)-gem.mp3', '%clip%egorythmia%new%level%'),
	('03-eight_sin_-_spirit-eup.mp3', '%eight%sin%spirit%'),
	('05-class_a_-_thats_strange_(static_movement_remix)-eup.mp3', '%class%thats%strange%static%movement%'),
	('07-ranji_-_maddness_control_(effective_remix)-eup.mp3', '%ranji%maddness%control%'),
	('Hippy_Cat_-_Astral_Airlines.mp3', '%Hippy%Cat%Astral%Airlines%'),
	('timmy_trumpet_and_scndl_-_bleed.mp3', '%timmy%trumpet%scndl%bleed%'),
	('02-talpa-perfect_psychopath_(original_mix).mp3', '%talpa%perfect%psychopath%'),
	('01-suntree_and_antigravity_-_o-beat-gem.mp3', '%suntree%antigravity%beat%'),
	('08-gaudium_-_one.mp3', '%gaudium - one%'),
	('01 - Angels of Destruction feat. Caroline Harrison (Neelix Remix).flac', '%Angels%Destruction%Caroline%'),
	('02-sideform_and_nerso-dune_(molok_remix).mp3', '%sideform%nerso%dune%'),
	('01-suntree_and_sphera-rush_hour-eup.mp3', '%suntree%sphera%rush%'),
	('02 - Little Stevie (Phaxe Remix).flac', '%Little%Stevie%Phaxe%'),
	('3. Wave After Wave (TCH - Underground Overground EP).wav', '%Wave%After%Wave%Underground%'),
	('01-rising_dust_-_sticks_of_glory-eup.mp3', '%rising%dust%sticks%glory%'),
	('01-talpa_-_booby_trap.mp3', '%talpa%booby%'),
	('01-ticon-extreme_memories.mp3', '%ticon%extreme%memories%'),
	('02-rising_dust_-_dust_everywhere-eup.mp3', '%rising%dust%dust%everywhere%'),
	('3. Wave After Wave (TCH - Underground Overground EP).wav', '%Wave%After%Wave%Underground%'),
	('01 - Soultool - Spread Your Wings (Original Mix).mp3', '%Soultool%Spread%Wings%'),
	('02 - Suntree And Sphera - Rush Hour-Eup.mp3', '%Suntree%Sphera%Rush%Hour%'),
	('03 - Vini Vici - Parallel Universe.mp3', '%Vin%Vici%Parallel%Universe%'),
	('04 - Vök - Before (Neelix Remix).mp3', '%Vök%Before%Neelix%'),
	('05 - Ismir - Stranger Feelings.mp3', '%Ismir%Stranger%Feelings%'),
	('06 - Wide Soul - Shift (Original Mix).mp3', '%Wide%Soul%Shift%'),
	('07 - Drop the Pain - My plans about you.mp3', '%Drop%Pain%plans%'),
	('08 - Sykick - Side Kick (Original Mix).mp3', '%Sykick%Side%Kick%'),
	('09 - Rocky - Origami.mp3', '%Rocky%Origami%'),
	('10 - Rocky - Among Us.mp3', '%Rocky%Among%'),
	('11 - Ace Ventura & Zen Mechanics - Come with Us (MVMB Remix).mp3', '%Ace%Ventura%Zen%Mechanics%Come%'),
	('12 - Ghost Rider - Music Is More.mp3', '%Ghost%Rider%Music%More%'),
	('13 - Highlight Tribe - Free Tibet (Vini Vici Remix).mp3', '%Highlight%Tribe%Free%Tibet%'),
	('14 - Metronome - Sadhana.mp3', '%Metronome%Sadhana%'),
	('15 - Berg - Soul Provider (Re-Edit).mp3', '%Berg%Soul%Provider%'),
	('16 - Headroom - Tech Byte Fever.mp3', '%Headroom%Tech%Byte%Fever%'),
	('17 - Vini Vici - Saturn.mp3', '%Vini%Vici%Saturn%'),
	('18 - Emok - Watching the World Go By.mp3', '%Emok%Watching%World%'),
	('19 - Atmos - Mint Beyond Surrender.mp3', '%Atmos%Mint%Beyond%Surrender%'),
	('20 - The Overlords - Gods Eye on Goa (Ticon Remix).mp3', '%Overlords%Gods%Eye%'),
	('21 - Animato - Simple Idea.mp3', '%Animato%Simple%Idea%'),
	('22 - Day Din - Lol (Original Mix).mp3', '%Day%Din% Lol%'),
	('23 - LOUD - Small Talk (Ozora Edit).mp3', '%LOUD%Small%Talk%'),
	('24 - Progenitor - Circles.mp3', '%Progenitor%Circles%'),
	('01 - X-Dream - The 1st Nanoplex Reboot.mp3', '%1st%Nanoplex%Reboot%'),
	('02 - Emok & Suntree - Catching the Moment.mp3', '%Emok%Suntree%Catching%the%Moment%'),
	('03 - Loud - Loose Senses (Mr. What! Remix).mp3', '% Loud%Loose%Senses%'),
	('04 - Lightsphere - Searchin For You.mp3', '%Lightsphere%Searchin%'),
	('05 - Mono - Power To The People (Original Mix).mp3', '%Mono%Power%People%'),
	('06 - Krama - Goth Beat.mp3', '%Krama%Goth%Beat%'),
	('07 - Fractal Glider - Twin Peaks (Original Mix).mp3', '%Fractal%Glider%Twin%Peaks%'),
	('08 - Ellinio And Orisma - Weed of Liana.mp3', '%Ellinio%Orisma%Weed%Liana%'),
	('09 - Liquid Soul & Electric Universe - Liquid Universe (Orison Remix).mp3', '%Electric%Universe%Liquid%Universe%'),
	('10 - E-Clip - Artificial Intelligence (Manmachine Remix).mp3', '%Clip%Artificial%Intelligence%Manmachine%'),
	('11 - Phaxe - Angels Of Destruction (Neelix Whatz Up Rmx).mp3', '%Phaxe%Angels%Destruction%Neelix'),
	('12 - Mono - Smile.mp3', '%Mono%Smile%'),
	('13 - Mono - Harder.mp3', '%Mono%Harder%'),
	('14 - Amagra - Bipolar.mp3', '%Amagra%Bipolar%'),
	('15 - Krama - Exhale the Past.mp3', '%Krama%Exhale%Past%'),
	('16 - O.T.B & Naughty Notes - Ganja People.mp3', '%Naughty%Notes%Ganja%People%'),
	('17 - Beat Herren Vs. PGM - Odyssee.mp3', '%Beat%Herren%Odyssee%'),
	('18 - Nikelodeon - Till The End.MP3', '%Nikelodeon%Till%End%'),
	('19 - Infuso - Riff & Pain.MP3', '%Infuso%Riff%Pain%'),
	('20 - Shiva Chandra - The White Raven.mp3', '%Shiva%Chandra%White%Raven%'),
	('21 - Oddwave - I m The One Who Knocks.mp3', '%Oddwave%Who%Knocks%'),
	('22 - Mono - Bloom.mp3', '%01.Bloom.mp3%'),
	('23 - Shiva Chandra - Coco Dupp.mp3', '%Shiva%Chandra%Coco%Dupp%'),
	('24 - Sixsense - Local Vibes.mp3', '%Sixsense%Local%Vibes%'),
	('01 - Suntree - The Future (Aerospace Remix).mp3', '%Suntree%Future%Aerospace%'),
	('02 - Sphera - We\'re Burning.mp3', '%Sphera%Burning%'),
	('03 - Durs - Aqualung.mp3', '%Durs%Aqualung%'),
	('04 - Gravitech - Fractures.mp3', '%Gravitech%Fractures%'),
	('05 - Lish - Star Scream.mp3', '%Lish%Star%Scream%'),
	('06 - Static Movement & Vertex - Its coming.mp3', '%Static%Movement%Vertex%coming%'),
	('07 - Critical Choice - Out Of Orbit (Suntree Remix).mp3', '%Critical%Choice%Out%Orbit%Suntree%'),
	('08 - Morten Granau - Spirit of Analogue.mp3', '%Morten%Granau%Spirit%Analogue%'),
	('09 - Microlin - The Secrets of Regeneration.flac', '%Microlin%Secrets%Regeneration%'),
	('10 - Shanti Matkin & Deedrah - Criminal Drug Evasion.mp3', '%Matkin%Deedrah%Criminal%Drug%'),
	('11 - Shanti Matkin & Deedrah vs GMS & MODERN8 - Nesting Too Deep.mp3', '%Shanti%Deedrah%Nesting%Deep%'),
	('12 - Mr. What! & Roger Rabbit - What Framed The Rabbit.mp3', '%What%Roger%Rabbit%Framed%'),
	('13 - Mr. What! - Out Of The Shadows.mp3', '%What%Out%Shadows%'),
	('14 - Lovegun - Time.mp3', '%Lovegun%Time%'),
	('15 - Out Of Jetlag - Quiet Your Mind.mp3', '%Out%Jetlag%Quiet%Mind%'),
	('16 - Surge & Autopilot - Destiny.mp3', '%Surge%Autopilot%Destiny%'),
	('17 - Sesto Sento & G.M.S - Blast A Rasta.mp3', '%Sento%Blast%Rasta%'),
	('18 - Space Cat & Volcano - Logical Imagination.mp3', '%Space%Cat%Volcano%Logical%Imagination%'),
	('19 - LOUD - Africa 101 (Original Mix).mp3', '%LOUD%Africa%101%'),
	('20 - Mighty Pills - Mentalist.flac', '%Mighty%Pills%Mentalist%'),
	('21 - Champa vs. Etcetera - Shrooms (Life Extension Remix).mp3', '%Champa%Etcetera%Shrooms%'),
	('22 - Reefer Decree - Out Of Bounds.flac', '%Reefer%Decree%Out%Bounds%'),
	('23 - Flowjob - Ashore (Safe At Last Version).mp3', '%Flowjob%Ashore%'),
	('24 - Julien Breitz - The Geeks Factory (Bedroom Track 2 Rev.A).flac', NULL),
	('17_Tropical_Bleyage-My_Thoughts.flac', '%Tropical%Bleyage%My%Thoughts%');
/*!40000 ALTER TABLE `DBFOOBOR` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
