CREATE TABLE `ALBUMS` (
	`ID_CD` INT(11) NOT NULL AUTO_INCREMENT,
	`CATEGORY` VARCHAR(32) NULL DEFAULT NULL,
	`FAMILY` VARCHAR(32) NULL DEFAULT NULL,
	`NAME` VARCHAR(255) NULL DEFAULT NULL,
	`ARTIST` VARCHAR(255) NULL DEFAULT NULL,
	`PATHNAME` VARCHAR(255) NULL DEFAULT NULL,
	`POSITION` VARCHAR(127) NULL DEFAULT NULL,
	`SUBPOSITION` VARCHAR(127) NULL DEFAULT NULL,
	`POSITIONHDD` VARCHAR(255) NULL DEFAULT NULL,
	`AUDIOTRACKS` INT(2) NULL DEFAULT NULL,
	`TRACKS` INT(2) NULL DEFAULT NULL,
	`CUE` INT(1) NULL DEFAULT NULL,
	`COVER` VARCHAR(255) NULL DEFAULT NULL,
	`PIC` INT(2) NULL DEFAULT NULL,
	`SIZE` INT(4) NULL DEFAULT NULL,
	`CD` INT(2) NULL DEFAULT NULL,
	`YEAR` VARCHAR(4) NULL DEFAULT NULL,
	`ISRC` VARCHAR(255) NULL DEFAULT NULL,
	`LABEL` VARCHAR(255) NULL DEFAULT NULL,
	`TAGISRC` VARCHAR(255) NULL DEFAULT NULL,
	`TAGLABEL` VARCHAR(255) NULL DEFAULT NULL,
	`STYLE` VARCHAR(255) NULL DEFAULT NULL,
	`COUNTRY` VARCHAR(32) NULL DEFAULT NULL,
	`LENGTHSECONDS` INT(4) NULL DEFAULT NULL,
	`LENGTHDISPLAY` VARCHAR(16) NULL DEFAULT NULL,
	`TYPEMEDIA` VARCHAR(32) NULL DEFAULT NULL,
	`SCORE` INT(2) NOT NULL DEFAULT 0,
	`TAGMETHOD` VARCHAR(3) NULL DEFAULT NULL,
	`ADD` DATETIME NULL DEFAULT NULL,
	`MODIFIED` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`ID_CD`),
	UNIQUE INDEX `ID_CD` (`ID_CD`),
	INDEX `FAMILY` (`FAMILY`),
	INDEX `CATEGORY` (`CATEGORY`),
	INDEX `STYLE` (`STYLE`),
	INDEX `NAME` (`NAME`),
	INDEX `ADD` (`ADD`)
)
COLLATE=`utf8_general_ci`
ENGINE=InnoDB
AUTO_INCREMENT=0
;

CREATE TABLE `TRACKS` (
	`ID_TRACK` INT(11) NOT NULL AUTO_INCREMENT,
	`ID_CD` INT(11) NOT NULL DEFAULT 0,
	`FILENAME` VARCHAR(255) NULL DEFAULT NULL,
	`PATHNAME` VARCHAR(255) NULL DEFAULT NULL,
	`LENGTHSECONDS` INT(4) NULL DEFAULT NULL,
	`LENGTHDISPLAY` VARCHAR(16) NULL DEFAULT NULL,
	`TYPEMEDIA` VARCHAR(32) NULL DEFAULT NULL,
	`TITLE` VARCHAR(255) NULL DEFAULT NULL,
	`ARTIST` VARCHAR(255) NULL DEFAULT NULL,
	`ALBUM` VARCHAR(255) NULL DEFAULT NULL,
	`DATE` VARCHAR(32) NULL DEFAULT NULL,
	`GENRE` VARCHAR(255) NULL DEFAULT NULL,
	`TRACKNUMBER` VARCHAR(6) NULL DEFAULT NULL,
	`ALBUMARTIST` VARCHAR(255) NULL DEFAULT NULL,
	`COMPOSER` VARCHAR(255) NULL DEFAULT NULL,
	`DISCNUMBER` VARCHAR(16) NULL DEFAULT NULL,
	`DISC` INT(2) NULL DEFAULT NULL,
	`TRACKORDER` VARCHAR(6) NULL DEFAULT NULL,
	`ISRC` VARCHAR(255) NULL DEFAULT NULL,
	`ORGANIZATION` VARCHAR(255) NULL DEFAULT NULL,
	`COUNTRY` VARCHAR(32) NULL DEFAULT NULL,
	`INDEX` VARCHAR(11) NULL DEFAULT NULL,
	`POS_START_SAMPLES` INT(11) NULL DEFAULT NULL,
	`POS_END_SAMPLES` INT(11)  NULL DEFAULT NULL,
	`SCORE` INT(2) NOT NULL DEFAULT 0,
	PRIMARY KEY (`ID_TRACK`),
	UNIQUE INDEX `ID_TRACK` (`ID_TRACK`),
	INDEX `ID_CD` (`ID_CD`)
)
COLLATE=`utf8_general_ci`
ENGINE=InnoDB
AUTO_INCREMENT=0
;

CREATE TABLE `COVERS` (
	`ID_CD` INT(11) NOT NULL,
	`NAME` VARCHAR(255) NOT NULL,
	`COVER` MEDIUMBLOB NOT NULL,
	`THUMBNAIL` MEDIUMBLOB NOT NULL,
	PRIMARY KEY (`ID_CD`),
	UNIQUE INDEX `ID_CD` (`ID_CD`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `FOOBAR` (
	`ID_FOO` INT(11) NOT NULL AUTO_INCREMENT,
	`ID_TRACK` INT(11) NULL,
	`PLAYLIST` VARCHAR(64) NOT NULL,
	`PATH` VARCHAR(255) NOT NULL,
	`ALBUM` VARCHAR(255) NULL DEFAULT NULL,
	`FILENAME` VARCHAR(255) NOT NULL,
	`NAME` VARCHAR(255) NULL DEFAULT NULL,
	`ARTIST` VARCHAR(255) NULL DEFAULT NULL,
	`TITLE` VARCHAR(255) NULL DEFAULT NULL,
	`ADD` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`ID_FOO`),
	UNIQUE INDEX `ID_FOO` (`ID_FOO`),
	INDEX `FILENAME` (`FILENAME`),
	INDEX `TAG_Album` (`NAME`, `ARTIST`, `TITLE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

CREATE VIEW VW_COMPLETION AS 
SELECT ID_CD, ARTIST AS SYNTHAX FROM ALBUMS WHERE ARTIST <> '' AND ARTIST <> 'Various'
UNION 
SELECT ID_CD, SUBPOSITION FROM ALBUMS WHERE FAMILY='Artists'
