CREATE TABLE `ALBUMS` (
	`ID_CD` INTEGER PRIMARY KEY AUTOINCREMENT,
	`CATEGORY` TEXT,
	`FAMILY` TEXT,
	`NAME` TEXT,
	`ARTIST` TEXT,
	`PATHNAME` TEXT,
	`POSITION` TEXT,
	`SUBPOSITION` TEXT,
	`POSITIONHDD` TEXT,
	`AUDIOTRACKS` INT,
	`TRACKS` INT,
	`CUE` INT,
	`COVER` TEXT,
	`PIC` INT,
	`SIZE` INT,
	`CD` INT,
	`YEAR` TEXT,
	`ISRC` TEXT,
	`LABEL` TEXT,
	`TAGISRC` TEXT,
	`TAGLABEL` TEXT,
	`STYLE` TEXT,
	`COUNTRY` TEXT,
	`LENGTHSECONDS` INT,
	`LENGTHDISPLAY` TEXT,
	`TYPEMEDIA` TEXT,
	`SCORE` INT,
	`TAGMETHOD` TEXT,
	`ADD` DATETIME,
	`MODIFIED` DATETIME);
CREATE INDEX ALBUMS_ndx_ADD ON ALBUMS(`ADD`);


CREATE TABLE `TRACKS` (
	`ID_TRACK` INTEGER PRIMARY KEY AUTOINCREMENT,
	`ID_CD` INT,
	`FILENAME` TEXT,
	`PATHNAME` TEXT,
	`LENGTHSECONDS` INT,
	`LENGTHDISPLAY` TEXT,
	`TYPEMEDIA` TEXT,
	`TITLE` TEXT,
	`ARTIST` TEXT,
	`ALBUM` TEXT,
	`DATE` TEXT,
	`GENRE` TEXT,
	`TRACKNUMBER` TEXT,
	`ALBUMARTIST` TEXT,
	`COMPOSER` TEXT,
	`DISCNUMBER` TEXT,
	`DISC` INT,
	`TRACKORDER` TEXT,
	`ISRC` TEXT,
	`ORGANIZATION` TEXT,
	`COUNTRY` TEXT,
	`INDEX` TEXT,
	`POS_START_SAMPLES` INT,
	`POS_END_SAMPLES` INT,
	`SCORE` INT);
CREATE INDEX TRACKS_ndx_IDCD ON ALBUMS(`ID_CD`);


CREATE TABLE FOOBAR(
	ID_FOO INTEGER PRIMARY KEY AUTOINCREMENT,
	`ID_TRACK` INT,
	`PLAYLIST` TEXT, 
	`PATH` TEXT, 
	`FILENAME` TEXT, 
	`NAME` TEXT,
	`ALBUM` TEXT,
	`ARTIST` TEXT, 
	`TITTLE` TEXT, 
	`ADD` DATETIME);
CREATE INDEX FOOBAR_ndx_FILENAME ON DBFOOBAR(FILENAME);


CREATE TABLE FOOBOR(
	FILENAME TEXT,
	FILENAMEM TEXT);


CREATE TABLE `COVERS` (
	`ID_CD` INT,
	`NAME` TEXT,
	`COVER` BLOB,
	`THUMBNAIL` BLOB);
CREATE INDEX COVERS_ndx_IDCD ON COVERS(`ID_CD`);


CREATE VIEW VW_COMPLETION AS
SELECT ID_CD, ARTIST AS SYNTHAX FROM ALBUMS WHERE ARTIST <> '' AND ARTIST <> 'Various'
UNION
SELECT ID_CD, LABEL FROM ALBUMS WHERE LABEL <> ''
UNION 
SELECT ID_CD, SUBPOSITION FROM ALBUMS WHERE FAMILY='Artists'
