USE [master]
GO


EXEC master.dbo.sp_addlinkedserver 
@server = N'HOMERSTATION5'
,@srvproduct=N'MySQL'
,@provider=N'MSDASQL'
,@provstr=N'DRIVER={MySQL ODBC 5.3 ANSI Driver};SERVER=homerstation;DATABASE=InventMP3;PORT=3306;USER=admInventMP3;PASSWORD=nuDbC6spVZxtkKC8;OPTION=134217728'
GO


EXEC master.dbo.sp_addlinkedserver 
@server = N'HOMERSTATION'
,@srvproduct=N'MySQL'
,@provider=N'MSDASQL'
,@provstr=N'DRIVER={MySQL ODBC 5.3 ANSI Driver};SERVER=homerstation;DATABASE=DBALBUMSMP3;PORT=3307;USER=AdmInvent;PASSWORD=JMctOz7a6TWnrJHB86pL;OPTION=134217728'
GO

-- test
SELECT * 
FROM openquery([HOMERSTATION5], 'SELECT * FROM InventMP3.COVERS')

SELECT * 
FROM openquery([HOMERSTATION], 'SELECT * FROM DBALBUMSMP3.COVERS')


-- copy table COVERS
INSERT INTO openquery([HOMERSTATION], 'SELECT * FROM DBALBUMSMP3.COVERS')
           ([ID_CD]
           ,[NAME]
           ,[COVER]
		   ,[THUMBNAIL])
SELECT     [ID_CD]
           ,[NAME]
           ,[COVER]
		   ,[THUMBNAIL]
FROM openquery([HOMERSTATION5], 'SELECT * FROM InventMP3.COVERS')


INSERT INTO openquery([HOMERSTATION], 'SELECT ID_CD,NAME,COVER,THUMBNAIL FROM DBALBUMSMP3.COVERS')
SELECT  *
FROM openquery([HOMERSTATION5], 'SELECT ID_CD,NAME,COVER,THUMBNAIL FROM InventMP3.COVERS WHERE ID_CD<>10760  AND ID_CD<>7463 AND ID_CD<>11034')