-- 3502
-- SELECT * FROM FOOBAR


-- -----------
-- TRACKS
-- -----------
-- SELECT * FROM FOOBAR WHERE ID_TRACK IS NOT NULL

-- selection playlist score 3 : 459 tracks
-- SELECT * FROM FOOBAR FOO WHERE LOCATE('Special\_Nouvelles_Ans', FOO.PATH)>0

UPDATE TRACKS TRK
-- SELECT * FROM TRACKS TRK
	INNER JOIN FOOBAR FOO
		ON FOO.FILENAME=TRK.FILENAME OR (FOO.TITLE = TRK.TITLE AND FOO.ARTIST = TRK.ARTIST AND FOO.TITLE <> '')
SET TRK.SCORE = 1,
FOO.ID_TRACK = TRK.ID_TRACK
WHERE LOCATE('Special\_Nouvelles_Ans', FOO.PATH)=0;


-- maj score track best track from FIL_Track
UPDATE TRACKS TRK
-- SELECT * FROM TRACKS TRK
	INNER JOIN FOOBAR FOO
		ON FOO.FILENAME=TRK.FILENAME OR (FOO.TITLE = TRK.TITLE AND FOO.ARTIST = TRK.ARTIST AND FOO.TITLE <> '')
SET TRK.SCORE = 3,
FOO.ID_TRACK = TRK.ID_TRACK
WHERE LOCATE('Special\_Nouvelles_Ans', FOO.PATH)>0;


-- -----------
-- ALBUMS
-- -----------
-- back score to top
UPDATE ALBUMS
INNER JOIN (SELECT ID_CD, MAX(SCORE) AS SCORE FROM TRACKS WHERE SCORE > 0 GROUP BY ID_CD) TRACKS
ON ALBUMS.ID_CD = TRACKS.ID_CD
SET ALBUMS.SCORE=TRACKS.SCORE
WHERE TRACKS.SCORE IS NOT NULL AND ALBUMS.SCORE<TRACKS.SCORE;


