
-- ##################
-- maj score track listen via FIL_Track
UPDATE DBTRACKS TRK
	INNER JOIN DBFOOBAR FOO
		ON FOO.FIL_Track=TRK.FIL_Track
SET TRK.Score = 1
WHERE char_length(FOO.Name)>14 AND TRK.Score=0;

-- ##################
-- maj score album=listen via FIL_Track
UPDATE DBALBUMS ALB
SET ALB.Score = 1
WHERE ALB.Score=0 AND ID_CD IN (
SELECT DISTINCT DBTRACKS.ID_CD FROM DBTRACKS
INNER JOIN DBFOOBAR
ON DBFOOBAR.FIL_Track=DBTRACKS.FIL_Track
WHERE char_length(DBFOOBAR.Name)>14);


-- ##################
-- maj score track best track from FIL_Track
UPDATE DBTRACKS TRK
	INNER JOIN DBFOOBAR FOO
		ON FOO.FIL_Track=TRK.FIL_Track
SET TRK.Score = 3
WHERE char_length(FOO.Name)<=14 AND TRK.Score<>3;


-- ##################
-- maj score album best from FIL_Track
UPDATE DBALBUMS ALB
SET ALB.Score = 3
WHERE ALB.Score<>3 AND ID_CD IN (
SELECT DISTINCT DBTRACKS.ID_CD FROM DBTRACKS
INNER JOIN DBFOOBAR
ON DBFOOBAR.FIL_Track=DBTRACKS.FIL_Track
WHERE char_length(DBFOOBAR.Name)<=14);


-- ##################
-- maj score track listen from TAGs artist, title
UPDATE DBTRACKS
INNER JOIN DBFOOBAR
	ON  DBFOOBAR.TAG_Artists = DBTRACKS.TAG_Artists AND DBFOOBAR.TAG_Title = DBTRACKS.TAG_Title AND DBTRACKS.Score=0
SET DBTRACKS.Score=1
WHERE DBFOOBAR.TAG_Artists<>'' AND DBFOOBAR.TAG_Title<>'';


-- ##################
-- maj best selection from TAGs artist, title
UPDATE DBTRACKS
INNER JOIN DBFOOBAR
	ON  DBFOOBAR.TAG_Artists = DBTRACKS.TAG_Artists AND DBFOOBAR.TAG_Title = DBTRACKS.TAG_Title
SET DBTRACKS.Score=3
WHERE DBTRACKS.Score<>3 AND  char_length(DBFOOBAR.Name)<=14 AND LEFT(DBFOOBAR.Name,4)='part' AND  DBFOOBAR.TAG_Artists<>'' AND DBFOOBAR.TAG_Title<>'';


-- ##################
-- Best Tracks Orphelins
-- SELECT DISTINCT DBFOOBAR.FIL_Track, DBFOOBAR.TAG_Album, DBFOOBAR.TAG_Artists, DBFOOBAR.TAG_Title, T1.FIL_TRACK, T2.FIL_TRACK AS TAGs, T3.FIL_TRACK AS ORPH FROM DBFOOBAR
-- LEFT JOIN DBTRACKS T1	ON (DBFOOBAR.FIL_Track=T1.FIL_Track) 
-- LEFT JOIN DBTRACKS T2	ON (DBFOOBAR.TAG_Artists = T2.TAG_Artists AND DBFOOBAR.TAG_Title = T2.TAG_Title AND DBFOOBAR.TAG_Artists<>'' AND DBFOOBAR.TAG_Title<>'')
-- LEFT JOIN DBFOOBOR 	ON DBFOOBAR.FIL_Track=DBFOOBOR.FIL_Track
-- LEFT JOIN DBTRACKS T3	ON REPLACE(T3.FIL_Track,'_',' ') LIKE DBFOOBOR.FIL_TrackM
-- WHERE char_length(DBFOOBAR.Name)<=14 AND LEFT(DBFOOBAR.Name,4)='part' AND T1.FIL_TRACK IS NULL AND T2.FIL_TRACK IS NULL AND T3.FIL_TRACK IS NULL;


-- ##################
-- update score from DBFOOBOR
UPDATE DBTRACKS
INNER JOIN DBFOOBOR 
	ON REPLACE(DBTRACKS.FIL_Track,'_',' ') LIKE DBFOOBOR.FIL_TrackM
SET DBTRACKS.Score=3
WHERE DBTRACKS.Score<>3;


-- ##################
-- maj score album listen from Album Name
UPDATE DBALBUMS 
INNER JOIN DBFOOBAR
	ON DBALBUMS.MD5=DBFOOBAR.MD5
SET DBALBUMS.Score = 1
WHERE DBALBUMS.Score=0 AND char_length(DBFOOBAR.Name)>14;


-- ################
-- maj score album from score track
UPDATE DBALBUMS 
INNER JOIN (SELECT ID_CD, MAX(DBTRACKS.Score) As Score FROM DBTRACKS GROUP BY ID_CD) DBT
	ON DBT.ID_CD=DBALBUMS.ID_CD
SET DBALBUMS.SCore=DBT.Score
WHERE DBALBUMS.SCore=0;
